[package]
name = "guessing_game"
version = "0.1.0"
authors = ["AlanCoding <arominge@redhat.com>"]
edition = "2018"
default-run = "guessing_game"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
